### ISSUE TITLE
The retweetbot doesn't read the json file properly

### ISSUE THREAD

**Issue by ahmadyousefdev** [mrbellek/twitterbot#15]
Hi,
First, Thank you for this amazing app.
In my code, I specefied a json file with this command: `sSettingsFile` but the problem is, it doesn't read it properly, for example:
in the filter section in my json file I have:
```
"filters": [
"t.co", "goo.gl" ,"http", "https",".com",".net",
],
```
and other words,, but it still showing tweets with those words..

In dice section I have:
```
"dice": {
		"media": 1.0,
		"urls": 0.0,
		"mentions": 0.0,
		"base": 0.7
	}
```
but I can clearly see links and mentions after executing my app

If I have to add something, I duplicated the  retweetbot example and used it, I only changed the words and data in the json file and the main php file.

**Comment by mrbellek** [comment]
Hi! If I understand correctly, you're trying to filter out retweeting links and mentions. Twitter has a built-in filter for that, which you can use in your search string: "filter:links".
The dice values should be correct. Can you let me know if using the above filter helps?

**Comment by ahmadyousefdev** [comment]
The filter `-filter:links` did what I'm looking for ! 😃
So, I can skip `"filters": []` from the json file and put the filters in my search string like this:
```
'aSearchStrings'   => array(
      1 => '"search word" -(words to filter)',
   ),
```
Thank you again for this amazing code 👍

**Comment by mrbellek** [comment]
That's right.
Thanks! I'm so happy you like it. :)
