### ISSUE TITLE
Where can I host a bot script?

### ISSUE THREAD

**Issue by TheAdnan** [mrbellek/twitterbot#16]
Are there any free solutions for hosting a PHP bot script? I know about hosting a node.js bot on Heroku, but I'm not sure if Heroku is a good fit for a PHP script. Any suggestions?

**Comment by mrbellek** [comment]
Hi there, it looks like Heroku does indeed support PHP on free accounts: https://devcenter.heroku.com/articles/getting-started-with-php#introduction

**Comment by TheAdnan** [comment]
@mrbellek yeah I've come across that, but they'd still charge you if you pass their monthly limit. Where have you hosted your bots?

**Comment by mrbellek** [comment]
My hosting is pcextreme.nl (Dutch), but only static html pages can use a free plan. €2/month for hosting without a domain, €10/month with domain.

https://www.pcextreme.nl/webhosting/classic

**Comment by TheAdnan** [comment]
Thanks for the info @mrbellek 🌷
