### ISSUE TITLE
Prevent duplicate tweets

### ISSUE THREAD

**Issue by offtrolley** [mrbellek/twitterbot#21]
When someone retweets the same content, say 3 times, is it possible to prevent the retweet bot retweeting all three posts ?

**Comment by mrbellek** [comment]
Sorry, I don't think so. That would involve keeping track of all users and their retweeted content, as well as an arbitrary treshold to determine if a tweet was soon enough after the previous one to be a 'duplicate'. That's too much work, for something Twitter itself already keeps track of - it'll prevent you from (re)tweeting something again if it's a duplicate status.
