### ISSUE TITLE
logger.inc.php

### ISSUE THREAD

**Issue by apps4research** [mrbellek/twitterbot#22]
this file is missing ... called by logger.php

**Comment by mrbellek** [comment]
You need to make that file yourself. It should define constants for your database credentials. You need DB_LOGGER_HOST/DB_LOGGER_USER/DB_LOGGER_NAME/DB_LOGGER_PASS.

**Comment by apps4research** [comment]
Yes figured it ... maybe good idea to add  that to the read me. Thanks for the nice scripts set :)

**Comment by mrbellek** [comment]
Good point. I've created #20 to add this.
