### ISSUE TITLE
Filters

### ISSUE THREAD

**Issue by offtrolley** [mrbellek/twitterbot#24]
Using the json filter file:
"filters": [
"#alternative",
"blockchain",
"gaming"
],
Hoping this will exclude tweets with the hashtag #alternative kind of works. 
However, it also excludes #alternativemusic or #alternativeclothing
Is there a way to make the match more exact.
Thanks

**Comment by mrbellek** [comment]
Hello, currently the filter is just an exact string match. You could try making the filters like '#alternative ' (with trailing space) as a workaround.

**Comment by offtrolley** [comment]
Thanks
